### PR TITLE
changed user to root

### PR DESCRIPTION
**Pull request by thundergreen**
user pi has not enough permissions to get this working

### CODE REVIEW

**Comment by thundergreen** [comment]
According to issue https://github.com/Psychokiller1888/snipsLedControl/issues/43

**Comment by Psychokiller1888** [comment]
No you can't do that, it messes the logs then. I'll add it to the respeaker core v2 installer instead

**Comment by thundergreen** [comment]
But it nly works this way with my reaspeaker array v2. what would be the right way to go?

**Comment by Psychokiller1888** [comment]
https://github.com/Psychokiller1888/snipsLedControl/commit/54746222a1abf0923ce13285fc9876a39e5aef17

**Pull request closed without merging**
